/* Generated by S-function Builder */
#ifndef _LSM303_BUS_H_
#define _LSM303_BUS_H_
/* Read only - STARTS */
#include "tmwtypes.h"




#ifndef _DEFINED_TYPEDEF_FOR_accel_
#define _DEFINED_TYPEDEF_FOR_accel_ 
typedef struct {
  real_T x;
  real_T y;
  real_T z;
} accel;
#endif


#ifndef _DEFINED_TYPEDEF_FOR_compass_
#define _DEFINED_TYPEDEF_FOR_compass_ 
typedef struct {
  real_T x;
  real_T y;
  real_T z;
} compass;
#endif

/* Read only - ENDS */


#endif
